name: vale-linting
on:
  push:
    branches:
    - master
    - vale-config
  pull_request:
  # Makes it possible to run from the Actions tab
  workflow_dispatch:

jobs:
  prose:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-check
        vale_flags: "--glob='!*{fr}*'"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
